// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Checkbox {

    [default_interface]
    runtimeclass CheckboxView {
        CheckboxView(Microsoft.ReactNative.IReactContext context);
        void UpdateProperties(Microsoft.ReactNative.IJSValueReader reader);
    };
}
